# Generated by Django 4.0.4 on 2022-04-12 17:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=300, primary_key=True, serialize=False),
        ),
    ]
