# Generated by Django 4.0.4 on 2022-04-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_food_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='food',
            field=models.ManyToManyField(to='shop.food'),
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.CharField(max_length=900),
        ),
    ]
