# Generated by Django 4.0.4 on 2022-04-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_food_alter_order_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='food',
            new_name='foods',
        ),
        migrations.AlterField(
            model_name='order',
            name='data',
            field=models.JSONField(max_length=900),
        ),
    ]
