# Generated by Django 4.0.3 on 2022-04-04 14:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=500, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('picture', models.FileField(upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
